const products = [
    {
        id: 1,
        name: 'CROSS THE STREET TEE',
        price: '310.000₫',
        like: true,
        img: require('../assets/1.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 2,
        name: 'DOODLE TEE',
        price: '310.000₫',
        like: false,
        img: require('../assets/2.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 3,
        name: 'MARCUS THROUGH THE NIGHT TEE',
        price: '310.000₫',
        like: false,
        img: require('../assets/3.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 4,
        name: 'MARCUS WISH TEE',
        price: '355.000₫',
        like: false,
        img: require('../assets/4.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 5,
        name: 'MONA MARCUS TEE',
        price: '332.000₫',
        like: false,
        img: require('../assets/5.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 6,
        name: 'KASSIDY BEACH TEE',
        price: '332.000₫',
        like: false,
        img: require('../assets/6.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 7,
        name: 'GYP EMBROIDERED TEE',
        price: '310.000₫',
        like: false,
        img: require('../assets/7.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 8,
        name: 'CLIMBING TEE',
        price: '242.000₫',
        like: false,
        img: require('../assets/8.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 9,
        name: 'SIGNATURE WASH POLO SHIRTS',
        price: '405.000₫',
        like: false,
        img: require('../assets/9.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 10,
        name: 'LIQUID WASH TEE',
        price: '378.000₫',
        like: false,
        img: require('../assets/10.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 11,
        name: 'THUNDER WASH TEE',
        price: '405.000₫',
        like: false,
        img: require('../assets/11.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 12,
        name: 'FALL APART WASHED TEE',
        price: '378.000₫',
        like: false,
        img: require('../assets/12.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 13,
        name: 'MOONCHILD WASHED TEE',
        price: '405.000₫',
        like: false,
        img: require('../assets/13.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 14,
        name: 'FLOWER BOGO TEE',
        price: '199.000₫',
        like: false,
        img: require('../assets/14.png'),
        about: 'Street wear unis3x.',
    },
    {
        id: 15,
        name: 'NOSTALGIA WASHED TEE',
        price: '276.000₫',
        like: false,
        img: require('../assets/15.png'),
        about: 'Street wear unis3x.',
    },
];

export default products;